"""empty message

Revision ID: 0e48e920bf37
Revises: fdb6d0473c24
Create Date: 2017-10-04 22:30:34.359752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e48e920bf37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Friends',
    sa.Column('user_to', sa.Integer(), nullable=False),
    sa.Column('user_from', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_from'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['user_to'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('user_to', 'user_from')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Friends')
    op.drop_table('Users')
    op.drop_table('Bets')
    # ### end Alembic commands ###
