"""empty message

Revision ID: 24aea80108f4
Revises: 
Create Date: 2017-09-24 17:45:42.591932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24aea80108f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bets')
    # ### end Alembic commands ###
