"""empty message

Revision ID: 764dadce9dd1
Revises: 
Create Date: 2017-09-28 01:16:36.519727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764dadce9dd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('bets')
    # ### end Alembic commands ###
